services:
  db:
    image: postgres:17
    container_name: qjobs_postgres
    env_file:
      - .env
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    build: .
    command: ["yarn", "dev"]
    env_file:
      - .env
    ports: ["3000:3000"]
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  postgres_data: